#!/usr/bin/env python


SOURCES='ctl_arrive_leave_player.c ctl_change_channel.c ctl_change_player.c ctl_create_delete_channel.c ctl_kickban.c ctl_messages.c ctl_registrations.c ctl_server_info.c ctl_stats.c'

ctl_packets = bld.new_task_gen()
ctl_packets.features = "cc cstaticlib"
ctl_packets.source = SOURCES
ctl_packets.target = "control_packets"
ctl_packets.includes = ' . .. '
ctl_packets.defines = ['_GNU_SOURCE', '_BSD_SOURCE']
ctl_packets.uselib = 'LIBCONFIG PTHREAD LIBDBI OPENSSL'
ctl_packets.install_path = None
