#!/usr/bin/env python


SOURCES='db_channel.c db_privilege.c db_registration.c db_server.c db_tools.c'

database = bld.new_task_gen()
database.features = "cc cstaticlib"
database.source = SOURCES
database.target = "database"
database.includes = ' . .. '
database.defines = ['_GNU_SOURCE', '_BSD_SOURCE']
database.uselib = 'LIBCONFIG PTHREAD LIBDBI OPENSSL'
database.install_path = None
