#!/usr/bin/env python


SOURCES='db_channel.c db_privilege.c db_registration.c db_server.c db_tools.c'

ctl_packets = bld.new_task_gen()
ctl_packets.features = "cc cstaticlib"
ctl_packets.source = SOURCES
ctl_packets.target = "database"
ctl_packets.includes = ' . .. '
ctl_packets.defines = ['_GNU_SOURCE', '_BSD_SOURCE']
ctl_packets.uselib = 'LIBCONFIG PTHREAD LIBDBI OPENSSL'
